[[main]]
  identifier = "docs"
  name = "Course Materials"
  url = "materials"
  weight = 1

[[main]]
  identifier = "schedule"
  name = "Schedule"
  url = "materials/schedule"
  weight = 2
  
[[main]]
  identifier = "slack"
  name = "Slack"
  url = "http://smi-eco280-02-202101.slack.com"
  weight = 3