baseurl = "https://eco280smith.netlify.app/"
languageCode = "en-us"
title = "ECO 280"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 1
    
[[menu.main]]
    name = "Assignments"
    url = "/assignments/"
    weight = 2
    
[[menu.main]]
    name = "Homework"
    url = "/homework/"
    weight = 3
    
[[menu.main]]
    name = "Slack"
    url = "smi-eco280-02-202101.slack.com"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "eco280logo.png"
    width = 50
    height = 50
    alt = "Logo"

