---
title: "Organization/Classification of the literature"
author: "Susan Sayre"
date: "9/16/2020"
output: 
  md_document:
    preserve_yaml: true
---

Make a copy of the [paper organization template](https://docs.google.com/spreadsheets/d/1snGY44o8JOzTPyKSl4siJj2j_s04Mob3kJXwsN0_plA/copy?usp=sharing) demonstrated in class to use for your own organization. The columns in the spreadsheet suggest useful information you may want to record about the different studies you're looking at, but no generic categories will work for all literature reviews. I encourage you to modify, add, or reorganize columns as you see fit. For instance, I used the "type of paper" column to distinguish between empirical papers and theory papers. For many topics, all the papers might be of one type or the other, so you might decide to delete this column or adapt it to record a sub-type. For instance, if all the papers are theoretical, we might want to use it to distinguish between dynamic or static models. Or if all the papers are empirical, perhaps an important distinction would be between papers that use cross-section data vs those using panel data. The relevant categories are specific to the topic of the literature review. 

As with the AIC exercise, the organizing spreadsheet is intended as a working tool for you. You do not need to submit the spreadsheet to me. It is designed to help you organize the papers you are looking at to make it easier to identify the themes you want to use to organize your presentation of the literature on your topic next week and your final literature review paper.